# Generated by Django 3.2 on 2022-09-17 11:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='题干')),
                ('choice', models.TextField(verbose_name='选项')),
                ('answer', models.IntegerField(verbose_name='答案')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='主键')),
                ('questions', models.TextField(verbose_name='关联的题目类')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='主键')),
                ('choice', models.TextField(verbose_name='选项的乱序')),
                ('answer', models.TextField(verbose_name='新组成的答案列表')),
                ('is_pass', models.BooleanField(default=False, verbose_name='是否通过')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answer.test')),
            ],
        ),
    ]
