# Generated by Django 3.2 on 2022-09-18 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.DateField(default=datetime.datetime(2022, 9, 18, 10, 49, 7, 462480), verbose_name='上传日期'),
        ),
    ]
