# Generated by Django 3.2 on 2022-09-17 11:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('openid', models.CharField(blank=True, default=None, max_length=28, null=True, unique=True, verbose_name='微信id')),
                ('id_card', models.CharField(max_length=18, null=True, verbose_name='身份证号')),
                ('student_number', models.CharField(max_length=12, unique=True, verbose_name='学号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('have_info', models.BooleanField(default=False, verbose_name='是否有信息')),
                ('have_report_info', models.BooleanField(default=False, verbose_name='是否有报道信息')),
                ('check_in', models.BooleanField(default=False, verbose_name='报道情况')),
                ('status', models.IntegerField(choices=[(0, '待审核'), (1, '已通过'), (-1, '被驳回'), (2, '未准备')], default=2, verbose_name='审核状态')),
                ('send_info', models.TextField(default='', verbose_name='发送数据')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.student')),
                ('hs', models.ImageField(blank=True, default='static/none.jpg', upload_to='static/new/hs', verbose_name='核酸检测结果')),
                ('health_code', models.ImageField(blank=True, default='static/none.jpg', upload_to='static/new/health_code', verbose_name='健康码')),
                ('tour_code', models.ImageField(blank=True, default='static/none.jpg', upload_to='static/new/tour_code', verbose_name='行程码')),
                ('photo', models.ImageField(blank=True, default='static/none.jpg', upload_to='static/new/photo', verbose_name='本人照片')),
                ('number', models.IntegerField(default=0, verbose_name='已经上传的照片数量')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.student')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=1, verbose_name='性别')),
                ('ethnic', models.CharField(choices=[('汉族', '汉族'), ('蒙古族', '蒙古族'), ('回族', '回族'), ('藏族', '藏族'), ('维吾尔族', '维吾尔族'), ('苗族', '苗族'), ('彝族', '彝族'), ('壮族', '壮族'), ('布依族', '布依族'), ('朝鲜族', '朝鲜族'), ('满族', '满族'), ('侗族', '侗族'), ('瑶族', '瑶族'), ('白族', '白族'), ('土家族', '土家族'), ('哈尼族', '哈尼族'), ('哈萨克族', '哈萨克族'), ('傣族', '傣族'), ('黎族', '黎族'), ('傈僳族', '傈僳族'), ('佤族', '佤族'), ('畲族', '畲族'), ('高山族', '高山族'), ('拉祜族', '拉祜族'), ('水族', '水族'), ('东乡族', '东乡族'), ('纳西族', '纳西族'), ('景颇族', '景颇族'), ('柯尔克孜族', '柯尔克孜族'), ('土族', '土族'), ('达斡尔族', '达斡尔族'), ('仫佬族', '仫佬族'), ('羌族', '羌族'), ('布朗族', '布朗族'), ('撒拉族', '撒拉族'), ('毛南族', '毛南族'), ('仡佬族', '仡佬族'), ('锡伯族', '锡伯族'), ('阿昌族', '阿昌族'), ('普米族', '普米族'), ('塔吉克族', '塔吉克族'), ('怒族', '怒族'), ('乌孜别克族', '乌孜别克族'), ('俄罗斯族', '俄罗斯族'), ('鄂温克族', '鄂温克族'), ('德昂族', '德昂族'), ('保安族', '保安族'), ('裕固族', '裕固族'), ('京族', '京族'), ('塔塔尔族', '塔塔尔族'), ('独龙族', '独龙族'), ('鄂伦春族', '鄂伦春族'), ('赫哲族', '赫哲族'), ('门巴族', '门巴族'), ('珞巴族', '珞巴族'), ('基诺族', '基诺族'), ('其他', '其他'), ('外国血统', '外国血统')], max_length=10, verbose_name='民族')),
                ('the_religion', models.BooleanField(default=False, verbose_name='是否有宗教信仰')),
                ('religion', models.CharField(blank=True, max_length=100, null=True, verbose_name='宗教信仰')),
                ('origin', models.CharField(max_length=100, verbose_name='生源地')),
                ('postcode', models.CharField(max_length=6, verbose_name='邮政编码')),
                ('phone_number', models.CharField(max_length=11, verbose_name='电话')),
                ('political_landscape', models.CharField(choices=[('共青团员', '共青团员'), ('群众', '群众')], max_length=6, verbose_name='政治面貌')),
                ('father_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='父亲姓名')),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='母亲姓名')),
                ('father_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='父亲电话')),
                ('mother_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='母亲电话')),
                ('detailed_address', models.CharField(max_length=100, verbose_name='详细地址')),
                ('native_place', models.CharField(max_length=100, verbose_name='籍贯')),
                ('household_address', models.CharField(max_length=100, verbose_name='户籍地址')),
                ('qq', models.CharField(max_length=12, verbose_name='QQ号码')),
                ('wechat', models.CharField(blank=True, max_length=28, null=True, verbose_name='微信号')),
                ('student_number', models.CharField(max_length=12, verbose_name='学号')),
                ('dormitory_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='宿舍id')),
                ('student_class', models.CharField(blank=True, max_length=10, null=True, verbose_name='班级')),
            ],
        ),
        migrations.CreateModel(
            name='ReportInfo',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.student')),
                ('estimated_arrival_time', models.DateField(verbose_name='预计报道时间')),
                ('whether_delay_report', models.BooleanField(default=False, verbose_name='是否推迟报道')),
                ('delay_report_reason', models.TextField(blank=True, null=True, verbose_name='延迟报道的原因')),
                ('transportation', models.CharField(max_length=10, verbose_name='交通工具')),
                ('car_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='车次')),
            ],
        ),
    ]
