# Generated by Django 3.2 on 2022-09-18 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='check_in_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 10, 49, 7, 457613), verbose_name='报道时间'),
        ),
    ]
