# Generated by Django 3.2 on 2022-09-18 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_check_in_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='check_in_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='报道时间'),
        ),
    ]
